### ISSUE TITLE
Main Menu buttons not clickable except "Play"

### ISSUE THREAD

**Issue by danbraik** [Maaack/Godot-Game-Template#110] opened 2024-06-19 17:53 UTC
Hi, first thank you very much for your project which help me a lot !

On a fresh install from the Asset Library in Godot 4.3.dev6.official, I got a bug when running the project:

- all buttons react to the mouse over
- only the "Play" button is clickable, others (Options, Credits, Exit) are not clickable

I found a workaround:
In `MainMenu` scene, I detach the script from the node "`MainMenu/MenuContainer/VBoxContainer/MenuMargin/MenuButtons`"

it may be a bug with  the next release Godot 4.3

Have a nice day,

**Comment by danbraik** [comment] 2024-06-21 16:17
I retried a fresh install with the Godot 4.3-beta1,
now all buttons are clickable but there is no focus on "Play" on `MainMenu` or on "Resume" on `PauseMenu`

**Comment by danbraik** [comment] 2024-07-13 17:38
Hi, I think I misspoke: the bug concerns the `MainMenuWithAnimation` scene, it seems there is no bug in `MainMenu` scene (without animation). It seems that the fade in animation is broken the focus system.
So the best workaround to have joypad and keyboard navigation is just to use `MainMenu`

**Comment by Maaack** [comment] 2024-07-15 16:59
Thanks for the update! I'll try to fix this before the official 4.3 release.

**Comment by KaruroChori** [comment] 2024-07-16 05:45
Another linked issue, the back button will not appear in the demo using animations on the latest 4.3.

**Comment by Maaack** [comment] 2024-08-23 00:20
I tested the main menu with animations with the 4.3 full release, but I wasn't able to replicate the reported issues.

![main-menu-in-4 3](https://github.com/user-attachments/assets/9b0a76fc-e74e-4b03-832c-f08ec809843f)

@danbraik or @KaruroChori please let me know if there are still issues on your end, or if I misunderstood the original issue. Thanks!

**Comment by KaruroChori** [comment] 2024-08-23 03:46
I just tested the stable release for 4.3 and v0.8.2 of this plugin.  
The problem is still there. 
Running the scene `MainMenu.tscn` will result in all buttons showing and working.
Running `MainMenuWithAnimations.tscn` only play is working. 
Actually if you click very quickly left and right, the other buttons will also work. No idea why or what is going on.

**Comment by Maaack** [comment] 2024-08-23 15:13
@KaruroChori thanks for trying it out again. I've got some follow-up questions about your setup if you have a moment.

- Mac, Windows, or Linux? 

- Are you installing the template on an existing project (from inside Godot editor; the most common use), or starting a project from the template (from the Project Manager)?

![image](https://github.com/user-attachments/assets/40d6d7a1-1322-46fa-b9bb-4046a8c5a471)

- What rendering mode are you using for your new project?

![image](https://github.com/user-attachments/assets/0aa38831-6195-459f-99a7-9cd9f91781f1)


If there's anything else that you might think is relevant, feel free to mention it. I appreciate it!

**Comment by KaruroChori** [comment] 2024-08-23 15:48
Linux, I tested a fresh project installing the plugin, enabling it and copying files over as suggested.
The rendering mode is forward+.
The version I am using is the one also shipping with C#, but it should not really matter.

I tested it on the same system back when I first reported this issue using 4.2. That was working fine.

**Comment by Maaack** [comment] 2024-08-23 23:36
I'm also running a Linux machine. I tried the mono version, too. 

![Screenshot from 2024-08-23 16-27-08](https://github.com/user-attachments/assets/006d8633-19bd-4a1e-b2dc-29895a824220)
![image](https://github.com/user-attachments/assets/579dd53d-bb22-47ed-aa17-608639601eda)

I'm a little unsure what else I should try to recreate the problem. Let me know if you think of anything else. 

Sorry you keep experiencing this bug. I'm curious if deleting the `addons/maaacks_game_template/examples/` folder after copying helps with anything. I was experiencing some weird behavior in Godot 4.3 related to this, but it's probably unrelated to this bug.

**Comment by KaruroChori** [comment] 2024-08-24 02:18
Are you using x11 or wayland?

**Comment by Maaack** [comment] 2024-08-24 02:50
Thanks for trying it anyway.
I'm using the `x11` display server.

**Comment by KaruroChori** [comment] 2024-08-24 03:15
Yeah. Same here. Later I am going to check if it works on my laptop as I had a different distribution installed.
Could you share the full project of it working and possibly an exported executable for amd64?

**Comment by Maaack** [comment] 2024-08-24 16:22
Sure, I just tested again with the 9.0 release. Here are the links to both source zip files:
[v0.9.0](https://github.com/Maaack/Godot-Game-Template/archive/refs/tags/v0.9.0.zip)
[v0.8.2](https://github.com/Maaack/Godot-Game-Template/archive/refs/tags/v0.8.2.zip)

The executable is 36 mb zipped, and the limit here is 25, but it's available from itch.io: https://maaack.itch.io/godot-game-template#download

**Comment by KaruroChori** [comment] 2024-08-24 17:11
I can confirm, the compiled versions are not working either on the system I have been working on.
So it is a linux compatibility problem for at least some configurations.

**Comment by KaruroChori** [comment] 2024-08-24 17:15
I tested it using `mobile` and `compatibility`. It works. So it must be a vulkan bug in godot, not here.
I am running a 3090 with drivers `535.104.05` on here. And for vulkan my system is reporting `Vulkan Instance Version: 1.3.250`

**Comment by Maaack** [comment] 2024-08-24 18:19
I did not realize I was exporting my builds in `forward+`. They've been updated to `compatibility`.

I've been testing on an RTX 4060 (Driver: `555.58.02`) recently, but I just tested in the 4.3 editor, Forward+, on a GTX 970M (Driver: `470.256.02`, pretty old). Still didn't reproduce the problem. I have some other laptops I can pull out and try on later as well.

**Comment by KaruroChori** [comment] 2024-08-29 20:33
I tested this template on a different machine with debian 13 and the basic integrated graphics provided by Intel. 
It worked well in the `forward+` target. At this point it is clearly a compatibility issue/regression on the godot engine itself and not with your code specifically.

If I am able to isolate the issue a bit better I will try to open a bug report upstream.

**Comment by Maaack** [comment] 2024-08-29 22:03
Thanks for looking into it further! Since the bug is upstream, I'll close this issue. Though let me know if there's any help I can provide to isolate the bug.

**Comment by gbillus** [comment] 2024-09-12 07:31
Was just about to open an issue.
 Windows 10,
 all renderers,
with or without .net
godot 4.3
no errors just nonfunctional input
both existing project and fresh template install
 only main menu with animations.
 how strange. Thought I was going crazy.

**Comment by gbillus** [comment] 2024-09-13 01:36
Okay so I have news. I accidently fixed the issue, im not sure how. But more importantly, I committed to my repo before and after. I have the settings committed that would be necessary for a control group, to preform more granular tests for finer data on the issue... at least on my machine which was effected in the first place. I'm just taking a guess in the dark, but I moved the UI scaling slightly so it wouldn't overlap my background image. When I went to test my work, I loaded the animated scene by mistake and discovered that the input bug was somehow resolved. I could share the repo with you if it would be any use. I can also preform tests on builds if you lay out the instructions for me.

**Comment by KaruroChori** [comment] 2024-09-13 02:35
Could you share it please? In my case only switching from forward+ to the others worker. Or changing computer :D.
It would be nice to see how it goes with your modified version.

**Comment by gbillus** [comment] 2024-09-13 03:13
@KaruroChori 
I didn't modify the addon itself. In the editor, I just moved the position of MenuContainer on screen so it wouldn't overlap the picture and scaled it down so it would fit( at least I believe that is what fixed it). Before we theorize on it too much, why don't you take a look at the code and test the build on your setup. Since I literally just began development on this project, I made a public fork of my project up to this point so you, Dan, Maaack, and whoever else is interested, can easily take a look at what is going on.
Hopefully we can determine the actual cause and provide a fix for everyone affected.

https://github.com/gbillus/maaak-template-example-from-YAPLand

**Comment by KaruroChori** [comment] 2024-09-13 05:00
No they do not, only the play button which has focus automatically after the animation ends. Same situation as with the base template or my project based on it.

**Comment by gbillus** [comment] 2024-09-13 23:13
I have new data... Everything I said before, possibly complete nonsense. For I have found the cause for the issue on my end. I'm able to see it happen during runtime. I made a discovery, I had a regression when I started testing earlier. The menu just decided it wasn't working again. Apparently, it was a fluke that it was working, but this led to finding something more concrete. Desperate to find a solution, I started testing things one at a time to no avail. I realized that this looks exactly like a bug I have had in a commercial game before, so I tried unplugging my Xbox controller, and to my surprise, the menu works every time for me now. Of course that doesn't prove anything, but I made a second discovery, if I plug the same controller in(only one I have for testing atm), there is a 4 out of 5 chance that when it detects the controller, the interface will break. I have a new theory..... Somehow, I think, the controller interface is somehow colliding with the keyboard and mouse interface. So my next question: Does everyone have a controller plugged in while testing? What kind?

**Comment by gbillus** [comment] 2024-09-13 23:22
> No they do not, only the play button which has focus automatically after the animation ends. Same situation as with the base template or my project based on it. However, somehow not even mobile or compatibility will work.
> 
> Changing the callback mode for the menuanimationtree from force continuous to either dominant or recessive unlocks the input. Do I know what those values do? Absolutely not :D.

Interesting, if the menu animations were causing this, then that would explain why the regular main menu is unaffected. I was digging thru the input helper to look for an issue, I might try to figure out how the animations work instead.

**Comment by gbillus** [comment] 2024-09-13 23:36
I am almost certain it is related to the controller logic because that is what causes the play button to be selected in the first place. Something else interesting, if you plug in the controller and it doesn't work on that run, the menu wont actually break until it is reloaded(by going to another menu and then returning to main menu). The controller still wont work if it doesn't want to, but the mouse will and you can get in the options menu one time with it. It has to be the controller logic in the AnimatedMainMenu. Perhaps an unintended interaction with the animation player.....?

**Comment by gbillus** [comment] 2024-09-20 16:33
So I switched the callback mode to dominant in the menuanimationtree like Chori suggested, and that fixed the input lock up issue. But now when I export the project to windows(Debug), the A button doesnt work in the menu, but the d-pad does. Whats even stranger is that It works fine when ran from the editor, I didnt notice I had a problem until I exported a test build. Any of you come across this issue?

**Comment by Maaack** [comment] 2024-09-20 17:45
We've found regressions with both the builds and the engine of 4.3. I'd recommend trying the latest 4.4-dev2 version, and seeing if the issues are still present.

**Comment by Maaack** [comment] 2024-09-25 21:56
Issue was reported again over discord. Some more details were provided, so I will reopen to investigate if something can be done on the template side.

**Comment by Maaack** [comment] 2024-09-26 04:38
I'm able to recreate the bug with an XBox controller plugged in. Current hypothesis is that it is related to the `capture_focus.gd` script on the `MenuButtonsBoxContainer`, and some kind of unintended interaction with the `MenuAnimationPlayer`.

Thank you @gbillus for your debugging work. Also thanks to ille1 on discord. I'll continue looking into this and see if I can't fix it for the next release.

**Comment by Maaack** [comment] 2024-09-26 05:24
I found a fix before I was able to figure out why `lock` is being repeatedly updated to `false`. It seems likely that it is the `MenuAnimationPlayer`, specifically the `OpenMainMenu` animation, but it is not set to repeat.

The fix avoids calling `update_focus()` if the value of `lock` is not changed when it is updated.

**Closed** 2024-09-26 05:25 UTC
Labels: bug, help wanted
